/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedWeeklyReviewRouteImport } from './routes/_authed.weekly-review'
import { Route as AuthedTodayRouteImport } from './routes/_authed.today'
import { Route as AuthedTimerRouteImport } from './routes/_authed.timer'
import { Route as AuthedStatsRouteImport } from './routes/_authed.stats'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedRewardsRouteImport } from './routes/_authed.rewards'
import { Route as AuthedReferralRouteImport } from './routes/_authed.referral'
import { Route as AuthedRecoveryRouteImport } from './routes/_authed.recovery'
import { Route as AuthedProgressRouteImport } from './routes/_authed.progress'
import { Route as AuthedPlanRouteImport } from './routes/_authed.plan'
import { Route as AuthedPassportRouteImport } from './routes/_authed.passport'
import { Route as AuthedMeRouteImport } from './routes/_authed.me'
import { Route as AuthedLeaderboardRouteImport } from './routes/_authed.leaderboard'
import { Route as AuthedInsightsRouteImport } from './routes/_authed.insights'
import { Route as AuthedHealthRouteImport } from './routes/_authed.health'
import { Route as AuthedHabitsRouteImport } from './routes/_authed.habits'
import { Route as AuthedGoalsRouteImport } from './routes/_authed.goals'
import { Route as AuthedEventsRouteImport } from './routes/_authed.events'
import { Route as AuthedCrewRouteImport } from './routes/_authed.crew'
import { Route as AuthedCommunityRouteImport } from './routes/_authed.community'
import { Route as AuthedCheckInRouteImport } from './routes/_authed.check-in'
import { Route as AuthedChallengesRouteImport } from './routes/_authed.challenges'
import { Route as AuthedCalendarRouteImport } from './routes/_authed.calendar'
import { Route as AuthedBodyRouteImport } from './routes/_authed.body'
import { Route as AuthedAssistantRouteImport } from './routes/_authed.assistant'
import { Route as AuthedActivitiesRouteImport } from './routes/_authed.activities'
import { Route as AuthedCheckInDoneRouteImport } from './routes/_authed.check-in.done'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWeeklyReviewRoute = AuthedWeeklyReviewRouteImport.update({
  id: '/weekly-review',
  path: '/weekly-review',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTodayRoute = AuthedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTimerRoute = AuthedTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStatsRoute = AuthedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRewardsRoute = AuthedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReferralRoute = AuthedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRecoveryRoute = AuthedRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProgressRoute = AuthedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlanRoute = AuthedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPassportRoute = AuthedPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMeRoute = AuthedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLeaderboardRoute = AuthedLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInsightsRoute = AuthedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHealthRoute = AuthedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHabitsRoute = AuthedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGoalsRoute = AuthedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEventsRoute = AuthedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCrewRoute = AuthedCrewRouteImport.update({
  id: '/crew',
  path: '/crew',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCommunityRoute = AuthedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCheckInRoute = AuthedCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChallengesRoute = AuthedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBodyRoute = AuthedBodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAssistantRoute = AuthedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivitiesRoute = AuthedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCheckInDoneRoute = AuthedCheckInDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => AuthedCheckInRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/activities': typeof AuthedActivitiesRoute
  '/assistant': typeof AuthedAssistantRoute
  '/body': typeof AuthedBodyRoute
  '/calendar': typeof AuthedCalendarRoute
  '/challenges': typeof AuthedChallengesRoute
  '/check-in': typeof AuthedCheckInRouteWithChildren
  '/community': typeof AuthedCommunityRoute
  '/crew': typeof AuthedCrewRoute
  '/events': typeof AuthedEventsRoute
  '/goals': typeof AuthedGoalsRoute
  '/habits': typeof AuthedHabitsRoute
  '/health': typeof AuthedHealthRoute
  '/insights': typeof AuthedInsightsRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
  '/me': typeof AuthedMeRoute
  '/passport': typeof AuthedPassportRoute
  '/plan': typeof AuthedPlanRoute
  '/progress': typeof AuthedProgressRoute
  '/recovery': typeof AuthedRecoveryRoute
  '/referral': typeof AuthedReferralRoute
  '/rewards': typeof AuthedRewardsRoute
  '/settings': typeof AuthedSettingsRoute
  '/stats': typeof AuthedStatsRoute
  '/timer': typeof AuthedTimerRoute
  '/today': typeof AuthedTodayRoute
  '/weekly-review': typeof AuthedWeeklyReviewRoute
  '/check-in/done': typeof AuthedCheckInDoneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/activities': typeof AuthedActivitiesRoute
  '/assistant': typeof AuthedAssistantRoute
  '/body': typeof AuthedBodyRoute
  '/calendar': typeof AuthedCalendarRoute
  '/challenges': typeof AuthedChallengesRoute
  '/check-in': typeof AuthedCheckInRouteWithChildren
  '/community': typeof AuthedCommunityRoute
  '/crew': typeof AuthedCrewRoute
  '/events': typeof AuthedEventsRoute
  '/goals': typeof AuthedGoalsRoute
  '/habits': typeof AuthedHabitsRoute
  '/health': typeof AuthedHealthRoute
  '/insights': typeof AuthedInsightsRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
  '/me': typeof AuthedMeRoute
  '/passport': typeof AuthedPassportRoute
  '/plan': typeof AuthedPlanRoute
  '/progress': typeof AuthedProgressRoute
  '/recovery': typeof AuthedRecoveryRoute
  '/referral': typeof AuthedReferralRoute
  '/rewards': typeof AuthedRewardsRoute
  '/settings': typeof AuthedSettingsRoute
  '/stats': typeof AuthedStatsRoute
  '/timer': typeof AuthedTimerRoute
  '/today': typeof AuthedTodayRoute
  '/weekly-review': typeof AuthedWeeklyReviewRoute
  '/check-in/done': typeof AuthedCheckInDoneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authed/activities': typeof AuthedActivitiesRoute
  '/_authed/assistant': typeof AuthedAssistantRoute
  '/_authed/body': typeof AuthedBodyRoute
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/challenges': typeof AuthedChallengesRoute
  '/_authed/check-in': typeof AuthedCheckInRouteWithChildren
  '/_authed/community': typeof AuthedCommunityRoute
  '/_authed/crew': typeof AuthedCrewRoute
  '/_authed/events': typeof AuthedEventsRoute
  '/_authed/goals': typeof AuthedGoalsRoute
  '/_authed/habits': typeof AuthedHabitsRoute
  '/_authed/health': typeof AuthedHealthRoute
  '/_authed/insights': typeof AuthedInsightsRoute
  '/_authed/leaderboard': typeof AuthedLeaderboardRoute
  '/_authed/me': typeof AuthedMeRoute
  '/_authed/passport': typeof AuthedPassportRoute
  '/_authed/plan': typeof AuthedPlanRoute
  '/_authed/progress': typeof AuthedProgressRoute
  '/_authed/recovery': typeof AuthedRecoveryRoute
  '/_authed/referral': typeof AuthedReferralRoute
  '/_authed/rewards': typeof AuthedRewardsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/stats': typeof AuthedStatsRoute
  '/_authed/timer': typeof AuthedTimerRoute
  '/_authed/today': typeof AuthedTodayRoute
  '/_authed/weekly-review': typeof AuthedWeeklyReviewRoute
  '/_authed/check-in/done': typeof AuthedCheckInDoneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth'
    | '/onboarding'
    | '/activities'
    | '/assistant'
    | '/body'
    | '/calendar'
    | '/challenges'
    | '/check-in'
    | '/community'
    | '/crew'
    | '/events'
    | '/goals'
    | '/habits'
    | '/health'
    | '/insights'
    | '/leaderboard'
    | '/me'
    | '/passport'
    | '/plan'
    | '/progress'
    | '/recovery'
    | '/referral'
    | '/rewards'
    | '/settings'
    | '/stats'
    | '/timer'
    | '/today'
    | '/weekly-review'
    | '/check-in/done'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/onboarding'
    | '/activities'
    | '/assistant'
    | '/body'
    | '/calendar'
    | '/challenges'
    | '/check-in'
    | '/community'
    | '/crew'
    | '/events'
    | '/goals'
    | '/habits'
    | '/health'
    | '/insights'
    | '/leaderboard'
    | '/me'
    | '/passport'
    | '/plan'
    | '/progress'
    | '/recovery'
    | '/referral'
    | '/rewards'
    | '/settings'
    | '/stats'
    | '/timer'
    | '/today'
    | '/weekly-review'
    | '/check-in/done'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authed'
    | '/auth'
    | '/onboarding'
    | '/_authed/activities'
    | '/_authed/assistant'
    | '/_authed/body'
    | '/_authed/calendar'
    | '/_authed/challenges'
    | '/_authed/check-in'
    | '/_authed/community'
    | '/_authed/crew'
    | '/_authed/events'
    | '/_authed/goals'
    | '/_authed/habits'
    | '/_authed/health'
    | '/_authed/insights'
    | '/_authed/leaderboard'
    | '/_authed/me'
    | '/_authed/passport'
    | '/_authed/plan'
    | '/_authed/progress'
    | '/_authed/recovery'
    | '/_authed/referral'
    | '/_authed/rewards'
    | '/_authed/settings'
    | '/_authed/stats'
    | '/_authed/timer'
    | '/_authed/today'
    | '/_authed/weekly-review'
    | '/_authed/check-in/done'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/weekly-review': {
      id: '/_authed/weekly-review'
      path: '/weekly-review'
      fullPath: '/weekly-review'
      preLoaderRoute: typeof AuthedWeeklyReviewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/today': {
      id: '/_authed/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthedTodayRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/timer': {
      id: '/_authed/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof AuthedTimerRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stats': {
      id: '/_authed/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthedStatsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rewards': {
      id: '/_authed/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthedRewardsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/referral': {
      id: '/_authed/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthedReferralRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/recovery': {
      id: '/_authed/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof AuthedRecoveryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/progress': {
      id: '/_authed/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthedProgressRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plan': {
      id: '/_authed/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthedPlanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/passport': {
      id: '/_authed/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof AuthedPassportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/me': {
      id: '/_authed/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthedMeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leaderboard': {
      id: '/_authed/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthedLeaderboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/insights': {
      id: '/_authed/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthedInsightsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/health': {
      id: '/_authed/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthedHealthRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/habits': {
      id: '/_authed/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthedHabitsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/goals': {
      id: '/_authed/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthedGoalsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/events': {
      id: '/_authed/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthedEventsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/crew': {
      id: '/_authed/crew'
      path: '/crew'
      fullPath: '/crew'
      preLoaderRoute: typeof AuthedCrewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/community': {
      id: '/_authed/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthedCommunityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/check-in': {
      id: '/_authed/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthedCheckInRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/challenges': {
      id: '/_authed/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthedChallengesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/body': {
      id: '/_authed/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof AuthedBodyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/assistant': {
      id: '/_authed/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthedAssistantRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activities': {
      id: '/_authed/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthedActivitiesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/check-in/done': {
      id: '/_authed/check-in/done'
      path: '/done'
      fullPath: '/check-in/done'
      preLoaderRoute: typeof AuthedCheckInDoneRouteImport
      parentRoute: typeof AuthedCheckInRoute
    }
  }
}

interface AuthedCheckInRouteChildren {
  AuthedCheckInDoneRoute: typeof AuthedCheckInDoneRoute
}

const AuthedCheckInRouteChildren: AuthedCheckInRouteChildren = {
  AuthedCheckInDoneRoute: AuthedCheckInDoneRoute,
}

const AuthedCheckInRouteWithChildren = AuthedCheckInRoute._addFileChildren(
  AuthedCheckInRouteChildren,
)

interface AuthedRouteChildren {
  AuthedActivitiesRoute: typeof AuthedActivitiesRoute
  AuthedAssistantRoute: typeof AuthedAssistantRoute
  AuthedBodyRoute: typeof AuthedBodyRoute
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedChallengesRoute: typeof AuthedChallengesRoute
  AuthedCheckInRoute: typeof AuthedCheckInRouteWithChildren
  AuthedCommunityRoute: typeof AuthedCommunityRoute
  AuthedCrewRoute: typeof AuthedCrewRoute
  AuthedEventsRoute: typeof AuthedEventsRoute
  AuthedGoalsRoute: typeof AuthedGoalsRoute
  AuthedHabitsRoute: typeof AuthedHabitsRoute
  AuthedHealthRoute: typeof AuthedHealthRoute
  AuthedInsightsRoute: typeof AuthedInsightsRoute
  AuthedLeaderboardRoute: typeof AuthedLeaderboardRoute
  AuthedMeRoute: typeof AuthedMeRoute
  AuthedPassportRoute: typeof AuthedPassportRoute
  AuthedPlanRoute: typeof AuthedPlanRoute
  AuthedProgressRoute: typeof AuthedProgressRoute
  AuthedRecoveryRoute: typeof AuthedRecoveryRoute
  AuthedReferralRoute: typeof AuthedReferralRoute
  AuthedRewardsRoute: typeof AuthedRewardsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedStatsRoute: typeof AuthedStatsRoute
  AuthedTimerRoute: typeof AuthedTimerRoute
  AuthedTodayRoute: typeof AuthedTodayRoute
  AuthedWeeklyReviewRoute: typeof AuthedWeeklyReviewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedActivitiesRoute: AuthedActivitiesRoute,
  AuthedAssistantRoute: AuthedAssistantRoute,
  AuthedBodyRoute: AuthedBodyRoute,
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedChallengesRoute: AuthedChallengesRoute,
  AuthedCheckInRoute: AuthedCheckInRouteWithChildren,
  AuthedCommunityRoute: AuthedCommunityRoute,
  AuthedCrewRoute: AuthedCrewRoute,
  AuthedEventsRoute: AuthedEventsRoute,
  AuthedGoalsRoute: AuthedGoalsRoute,
  AuthedHabitsRoute: AuthedHabitsRoute,
  AuthedHealthRoute: AuthedHealthRoute,
  AuthedInsightsRoute: AuthedInsightsRoute,
  AuthedLeaderboardRoute: AuthedLeaderboardRoute,
  AuthedMeRoute: AuthedMeRoute,
  AuthedPassportRoute: AuthedPassportRoute,
  AuthedPlanRoute: AuthedPlanRoute,
  AuthedProgressRoute: AuthedProgressRoute,
  AuthedRecoveryRoute: AuthedRecoveryRoute,
  AuthedReferralRoute: AuthedReferralRoute,
  AuthedRewardsRoute: AuthedRewardsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedStatsRoute: AuthedStatsRoute,
  AuthedTimerRoute: AuthedTimerRoute,
  AuthedTodayRoute: AuthedTodayRoute,
  AuthedWeeklyReviewRoute: AuthedWeeklyReviewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
